[pytest]
markers =
    ui: UI tests
    api: API tests
addopts =
    -v
    --strict-markers
    --tb=short
    --allure dir=./allure-results
test paths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*