[pytest]
markers =
    ui: UI tests
    api: API tests
addopts =
    -v
    --strict-markers
    --tb=short
    --alluredir=./allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*